# Part 1

Haikal Ali_1103223071_TK46GAB

# Konvensi Umum dan Elemen API scikit-learn

Notebook ini dibuat dari materi **Common Conventions and API Elements of scikit-learn**.  
Bagian yang memiliki kode dibuat sebagai cell kode. Bagian yang tidak memiliki kode ditulis sebagai teori.

## Kebutuhan Teknis

Bab ini tidak memiliki kebutuhan teknis khusus.

## 1. Filosofi Desain scikit-learn

Desain scikit-learn berpusat pada beberapa prinsip utama: konsistensi, kesederhanaan, modularitas, dan reusabilitas. Sebagian besar model menggunakan pola antarmuka yang sama, yaitu `fit()` untuk melatih model, `predict()` untuk membuat prediksi, dan `transform()` untuk mengubah data.

Dengan pola yang konsisten ini, pengguna dapat berpindah dari satu model ke model lain dengan lebih mudah. scikit-learn juga bersifat modular, sehingga komponen seperti estimator, transformer, dan pipeline dapat digabungkan untuk membangun alur machine learning yang lebih rapi dan mudah digunakan ulang.

Contohnya, preprocessing seperti scaling dan encoding dapat digabungkan langsung dengan proses modeling menggunakan `Pipeline()`. Dengan begitu, preprocessing dan model dapat dikemas menjadi satu alur kerja yang lebih efisien dan mudah direproduksi.

Catatan penulisan: **scikit-learn** ditulis dengan huruf kecil.

## 2. Estimator

Estimator adalah objek dalam scikit-learn yang digunakan untuk belajar dari data. Estimator dapat berupa model atau transformer. Dua method utama pada estimator adalah:

- `fit()` untuk melatih model berdasarkan data
- `predict()` untuk membuat prediksi dari data baru

Contoh berikut menggunakan `LinearRegression()`.

In [1]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Data contoh
X = np.array([[1], [2], [3], [4], [5]])  # Matriks fitur
y = np.array([1, 2, 3, 3.5, 5])  # Nilai target

# Membuat dan melatih model
model = LinearRegression()
model.fit(X, y)

# Prediksi untuk data baru
X_new = np.array([[6], [7]])
predictions = model.predict(X_new)

print(predictions)

[5.75 6.7 ]


scikit-learn juga menyediakan method `fit_predict()`, yaitu shortcut yang menggabungkan proses `fit()` dan `predict()` dalam satu pemanggilan. Method ini biasanya digunakan ketika prediksi ingin diperoleh dari dataset yang sama dengan dataset yang digunakan untuk melatih model, terutama pada unsupervised learning.

Contoh berikut menggunakan `KMeans`.

In [2]:
from sklearn.cluster import KMeans

# Data contoh
X = np.array([[1], [2], [3], [4], [5]])

# Contoh clustering KMeans
kmeans = KMeans(n_clusters=2)
labels = kmeans.fit_predict(X)

print(labels)

[1 1 0 0 0]


Pola penggunaan scikit-learn tetap konsisten, baik untuk model sederhana seperti regresi linear maupun model yang lebih kompleks seperti random forest. Struktur utamanya tetap menggunakan `fit()` dan `predict()`.

## 3. Transformer dan Method `transform()`

Transformer adalah alat dalam scikit-learn yang digunakan untuk mengubah data, misalnya scaling, normalisasi, atau encoding sebelum data digunakan untuk modeling.

Transformer juga mengikuti pola yang konsisten:

- `fit()` digunakan untuk mempelajari parameter dari data
- `transform()` digunakan untuk menerapkan transformasi ke data

Contohnya, `StandardScaler()` menghitung mean dan standar deviasi pada proses `fit()`, lalu menggunakan nilai tersebut untuk melakukan scaling pada proses `transform()`.

In [3]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Data contoh
X = np.array([[1, 2], [3, 4], [5, 6]])

# Membuat instance StandardScaler
scaler = StandardScaler()

# Melakukan fit pada data
scaler.fit(X)

# Melakukan transformasi data
X_scaled = scaler.transform(X)

print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


Ada juga shortcut `fit_transform()` yang menggabungkan proses `fit()` dan `transform()` dalam satu langkah. Biasanya `fit_transform()` digunakan pada data training ketika data ingin langsung ditransformasi berdasarkan parameter yang dipelajari dari data training.

Untuk data test, transformer sebaiknya tidak di-`fit()` ulang. Data test cukup menggunakan `transform()` berdasarkan parameter yang sudah dipelajari dari data training agar transformasi tetap konsisten.

In [4]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Data contoh
X = np.array([[1, 2], [3, 4], [5, 6]])

# Membuat instance StandardScaler dan melakukan fit_transform dalam satu langkah
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


Konsistensi pada transformer membuatnya dapat digabungkan dengan pipeline machine learning. Dengan pipeline, transformasi yang sama dapat diterapkan pada data training dan data test secara lebih terstruktur.

## 4. Custom Estimator dan Custom Transformer

scikit-learn dirancang agar dapat diperluas. Developer dapat membuat custom estimator dan custom transformer yang tetap kompatibel dengan workflow scikit-learn.

Caranya adalah dengan menggunakan `BaseEstimator()` dan mixin class. Custom estimator sebaiknya mengikuti interface scikit-learn:

- Untuk transformer: implementasi `fit()` dan `transform()`
- Untuk model: implementasi `fit()` dan `predict()`

Dengan mengikuti struktur ini, custom object dapat digunakan bersama tools seperti `GridSearchCV()` dan `Pipeline()`.

Mixin adalah cara untuk menambahkan fungsi ke class tanpa mengulang kode yang sama. Fungsi umum dapat dikelompokkan ke dalam mixin, lalu digunakan oleh class yang membutuhkannya.

## 5. Pipeline dan Automasi Workflow

Dalam machine learning, workflow biasanya terdiri dari beberapa tahap berurutan, seperti preprocessing data, training model, dan prediksi. Di scikit-learn, `Pipeline()` digunakan untuk menggabungkan beberapa langkah tersebut ke dalam satu objek.

Pipeline membantu memastikan setiap proses dijalankan dalam urutan yang benar, mulai dari transformasi data sampai prediksi. Pipeline juga membuat workflow lebih mudah direproduksi dan mengurangi intervensi manual.

Dalam konteks MLOps, pipeline membantu proses pengembangan, pengujian, deployment, monitoring, dan retraining model agar lebih terstruktur.

### MLOps

MLOps adalah praktik mengintegrasikan workflow machine learning ke dalam siklus pengembangan dan operasi software. Tujuannya adalah membuat proses pengembangan, pengujian, deployment, dan pemeliharaan model menjadi lebih otomatis, scalable, reliable, dan sustainable.

MLOps penting karena membantu menjembatani pekerjaan data science, machine learning engineering, dan tim operasional. Selain itu, MLOps juga membantu mempercepat deployment, meningkatkan monitoring performa model, serta menangani masalah seperti model drift dan technical debt.

scikit-learn mendukung workflow MLOps melalui `Pipeline()`, `GridSearchCV()`, serta penyimpanan model menggunakan library seperti `joblib` dan `pickle`.

## 6. Atribut dan Method Umum

Model scikit-learn memiliki beberapa atribut dan method umum yang dapat digunakan untuk memahami hasil pembelajaran model.

Pada model linear, atribut seperti `coef_` dan `intercept_` digunakan untuk menyimpan koefisien dan intercept yang dipelajari oleh model. Method `score()` digunakan untuk mengevaluasi performa model. Pada regresi, `score()` biasanya menghasilkan nilai R-squared.

In [5]:
from sklearn.linear_model import LinearRegression
import numpy as np

# Data contoh
X = np.array([[1], [2], [3], [4], [5]])  # Matriks fitur
y = np.array([1, 2, 3, 3.5, 5])  # Nilai target

# Membuat dan melatih model
model = LinearRegression()
model.fit(X, y)

# Mengakses koefisien
print("Coefficients:", model.coef_)

# Mengakses intercept
print("Intercept:", model.intercept_)

# Menggunakan score() untuk mengevaluasi model
print("Model R-squared:", model.score(X, y))

Coefficients: [0.95]
Intercept: 0.04999999999999938
Model R-squared: 0.9809782608695652


Catatan: R-squared bisa menyesatkan dalam beberapa kasus karena nilainya dapat dipengaruhi oleh kondisi data. Nilai R-squared juga dapat meningkat ketika variabel tambahan dimasukkan ke dalam data. Karena itu, adjusted R-squared sering digunakan untuk memperhitungkan jumlah variabel.

## 7. Hyperparameter Tuning dengan Search Method

Hyperparameter tuning digunakan untuk mengoptimalkan model machine learning. scikit-learn menyediakan beberapa metode seperti `GridSearchCV()` dan `RandomizedSearchCV()`.

Selain itu, scikit-learn juga menyediakan pendekatan manual melalui `set_params()` dan `get_params()`:

- `set_params()` digunakan untuk mengatur hyperparameter model
- `get_params()` digunakan untuk melihat hyperparameter model saat ini

In [6]:
from sklearn.ensemble import RandomForestClassifier

# Membuat model RandomForestClassifier
model = RandomForestClassifier()

# Mengatur hyperparameter sebelum training menggunakan set_params()
model.set_params(n_estimators=100, max_depth=10, random_state=42)

# Mengecek parameter yang sudah diperbarui
print(model.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 10, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}


Output `get_params()` menampilkan detail hyperparameter model yang sedang digunakan. Informasi ini dapat digunakan untuk eksperimen konfigurasi model.

## 8. Metadata: Tags dan Metadata Routing

scikit-learn menggunakan metadata seperti estimator tags untuk mengatur bagaimana model bekerja dalam berbagai konteks, termasuk cross-validation dan pipeline. Tags juga dapat menunjukkan kemampuan estimator, misalnya apakah estimator dapat menangani multi-output data atau missing values.

Metadata dalam scikit-learn digunakan untuk mengatur aliran data antar proses dalam pipeline. Ada dua jenis objek metadata:

- Router: mengirim metadata
- Consumer: menggunakan metadata dalam perhitungan

Konsep ini disebut metadata routing.

Metadata routing memungkinkan informasi tambahan seperti sample weights, group labels, atau fit parameters diteruskan ke bagian tertentu dalam workflow. Misalnya, pada dataset tidak seimbang, sample weights dapat diteruskan ke classifier tanpa mengganggu langkah preprocessing seperti scaling.

## 9. Best Practices Penggunaan API scikit-learn

Beberapa praktik yang perlu diperhatikan saat menggunakan scikit-learn:

- **Uniform API**: Semua estimator mengikuti pola dasar `fit()`, `transform()` untuk transformer, dan `predict()` untuk prediksi.
- **Data preprocessing**: Data sebaiknya diproses terlebih dahulu menggunakan tools dari `sklearn.preprocessing`, seperti scaling, encoding, atau handling missing values.
- **Pipelines**: Untuk workflow yang terdiri dari banyak transformasi dan model, gunakan `Pipeline()` agar operasi dapat dirangkai dengan lebih rapi.
- **Cross-validation**: Evaluasi model menggunakan cross-validation dari `sklearn.model_selection` untuk memperkirakan kemampuan generalisasi model.
- **Hyperparameter tuning**: Gunakan `GridSearchCV()` atau `RandomizedSearchCV()` untuk mencari hyperparameter yang optimal.